{{- if .Values.ingress.enabled -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: cluster-argocd-server
  labels:
    {{- include "argocd.labels" . | nindent 4 }}
spec:
  rules:
    - host: argocd.public.k8s.local
      http:
        paths:
          - path: /
            backend:
              serviceName: cluster-argocd-server
              servicePort: http

{{- end }}
